name: iOS CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - test
  
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use local Flutter SDK
        run: echo "/Users/mohamedsalem/Developer/flutter/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: flutter pub get

      - name: Install CocoaPods
        working-directory: ios
        run: pod install --repo-update

      - name: Update bundler
        working-directory: ios
        run: gem install bundler

      - name: bundle install
        working-directory: ios
        run: bundle install

      - name: Setup key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY}}

      - name: ðŸ“± Build STAGING iOS Application
        run: bundle exec fastlane ios staging
        working-directory: ios
        env:
          CI: true
          # CHANGELOG:
          APP_STORE_APP_IDENTIFIER: com.company.scalablecicd.staging
          APP_NAME: "[Staging] ScalableCI|CD"
          SCHEME: staging
          ITC_TEAM_NAME: ${{ secrets.ITC_TEAM_NAME }}
          FASTLANE_ITC_TEAM_NAME: ${{ secrets.ITC_TEAM_NAME }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
          APP_STORE_TEAM_ID: ${{ secrets.TEAM_ID }}

      - name: Pilot builds
        run: bundle exec fastlane pilot builds -a com.company.scalablecicd.staging
        working-directory: ios
        env:
          CI: true 
          APP_STORE_APP_IDENTIFIER: com.company.scalablecicd.staging
          APP_NAME: "[Staging] ScalableCI|CD"
          SCHEME: staging
          ITC_TEAM_NAME: ${{ secrets.ITC_TEAM_NAME }}
          FASTLANE_ITC_TEAM_NAME: ${{ secrets.ITC_TEAM_NAME }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
          APP_STORE_TEAM_ID: ${{ secrets.TEAM_ID }}
          working-directory: ios