name: iOS CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
  
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: '3.1'

      - name: Check Ruby version
        run: ruby --version

      # - name: Install Flutter stable channel
      #   uses: subosito/flutter-action@v2
      #   id: flutter-action
      #   with:
      #     channel: stable
      # - run: flutter --version
      - name: Use local Flutter SDK
        run: echo "/Users/mohamedsalem/Developer/flutter/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: flutter pub get

      - name: Install CocoaPods
        working-directory: ios
        run: pod install --repo-update

      - name: bundle install
        working-directory: ios
        run: bundle install

      - name: Setup key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY}}

      # - name: Flutter version
      #   run: flutter doctor

      
      # - name: Analyze project source
      #   run: dart analyze

      # - name: Run tests
      #   run: flutter test

      # - name: Extract flavor from commit message
      #   id: extract_flavor
      #   run: |
      #     COMMIT_MSG=$(git log -1 --pretty=%B)
      #     echo "Commit message: $COMMIT_MSG"
      #     FLAVOR=$(echo "$COMMIT_MSG" | grep -oP '(?<=build:)\w+')
      #     echo "FLAVOR=$FLAVOR" >> $GITHUB_ENV

      - name: ðŸ“± Build STAGING iOS Application
        run: | 
            bundle exec fastlane ios staging
            bundle exec fastlane pilot builds
        working-directory: ios
        env:
          CI: true
          APP_STORE_APP_IDENTIFIER: com.company.scalablecicd.staging
          APP_NAME: "[Staging] ScalableCI|CD"
          SCHEME: staging
          ITC_TEAM_NAME: ${{ secrets.ITC_TEAM_NAME }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_USERNAME: ${{ secrets.MATCH_USERNAME }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_CONTENT: ${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}
          APP_STORE_TEAM_ID: ${{ secrets.TEAM_ID }}